# Generated by Django 2.1.7 on 2019-03-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='count',
            field=models.IntegerField(blank=True, default=0, verbose_name='包含的数量'),
        ),
    ]
