# Generated by Django 2.1.7 on 2019-03-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190313_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='edit_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='修改时间'),
        ),
    ]
